### PR TITLE
Pydantic validation revised

### PR DESCRIPTION
**Pull request by harmatt**
Includes revised pydantic validation and dataset validation, as well as additional helper validation functions

### CODE REVIEW

**Comment by afrubin** [comment]
@harmatt can you please have a look at the merge conflicts and see if you can sort them out?

**Comment by harmatt** [comment]
@afrubin , I resolved the merge conflicts and added @EstelleDa  as a reviewer

**Comment by EstelleDa** [comment]
I think all look good. Except one validation function, `validate_external_identifier`, in mavecore/validation/identifier.py need to change or we can leave this one in the future. For the rest, we can try to use them in MaveDB.

**Comment by harmatt** [comment]
Thanks @EstelleDa ! I agree, the validation in validate_external_identifier is ugly and deviates from the techniques used in the other validation. Pydantic has a way, using root_validator, to do this more elegantly, but I cannot seem to get it to work. You can see (commented out) how it should be implemented in mavecore/models/identifier.py

**Review by EstelleDa — APPROVED** [review]
Except one validation function, validate_external_identifier, in mavecore/validation/identifier.py need to change or we can leave this one in the future. The rest are all good.

**Pull request merged**
